name = "frontpage-api"
main = "src/worker.py"
compatibility_date = "2026-03-21"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "frontpage-db"
database_id = "2bc412e7-b033-4d83-940b-224305a323a2"

[vars]
ALLOWED_ORIGIN = "https://frontpage-generator.pages.dev"
PUBLIC_FONT_URL = "https://frontpage-generator.pages.dev/static/Sans.ttf"
PUBLIC_TEMPLATE_URL = "https://frontpage-generator.pages.dev/static/template.png"
